### ISSUE TITLE
GoAdmin && Firebase

### ISSUE THREAD

**Issue by MarErm27** [haoyuant/SwaggerLearn#1]
Hello, I was wondering if you could help me to find out how to use Firebase instead of other databases for GoAdmin?
Is there a built-in feature to send an email to users on the list of users?
How to change templates?

**Comment by haoyuant** [comment]
Hi, you can use any database you like for GoAdmin. You need to define your own generator, and handle your db operations in this function, which makes it like a DAO. You should be able to find the default generator whiten the GoAdmin source code. As for the email function, as far as I know, there is no such a thing, but it is not that hard to implement your own. In our project, we use mssql, and extend the database schema as well as the frontend UI to meet our own needs. So I suggest you to have a look at how GoAdmin connects the database, and how it render the frontend.

But I am not an expert, in fact my teammate did most of the work of this part, so I cannot get you a good tutorial.

By the way, I am happy to offer any helps, but just curious, how did you find me and why me?

**Comment by MarErm27** [comment]
I've found your post at GoAdmin repository, [here is it](https://github.com/GoAdminGroup/go-admin/issues/284)

Here is how the dashboard looks now:
![image](https://user-images.githubusercontent.com/56219126/92326963-c8856980-f05e-11ea-9933-837866def51b.png)

For now, I'm trying to simplify it to make it looks like this

![image](https://user-images.githubusercontent.com/56219126/92327094-e901f380-f05f-11ea-874d-660649041a70.png)

So instead of the main dashboard, there will be a table of users and the sidebar will contain fewer options

I can't find a way to change the sidebar. For a first step, I'm trying to delete the posts section. 
1) I've deleted the "posts" table from the SQLite database. 
2) I've commented out the code that generates this section [here](https://github.com/MarErm27/adminPortal/blob/master/tables/tables.go)
3) I've checked the code for the tmpl template [here](https://github.com/MarErm27/themes/blob/master/adminlte/separation/public/pages/sidebar.tmpl) but all the fields here is getting injected from the application. 
4) I've searched for the word "posts" in the entire project and I can't find any other usages except in Punkt 2 where I commented it out

I was wondering if you know the place where the sidebar can be modified and how to replace a dashboard with table with users

**Comment by MarErm27** [comment]
Hi, I've got this error# github.com/MarErm27/adminPortal

```
C:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: error: export ordinal too large: 82373
collect2.exe: error: ld returned 1 exit status
```

How to make export ordinal smaller?

I'm trying to connect to FireBase.
To do this I following the [guide](https://firebase.google.com/docs/admin/setup#go)

So 
1) I installed the module dependency
go get firebase.google.com/go/v4
2) downloaded the JSON file
3) set the environment variable
4) and launched this code

```
package app

import (
	firebase "firebase.google.com/go"
	"fmt"
	"golang.org/x/net/context"
	"log"
)

func Authentificate() {
	app, err := firebase.NewApp(context.Background(), nil)
	if err != nil {
		log.Fatalf("error initializing app: %v\n", err)
	}
	fmt.Println("app: ", app)
}
```

And I got the error above. Have you encountered this?

**Comment by haoyuant** [comment]
We didn't do much customisation in our project, but if you want to custom your table rows and edit forms, here is the right place to look at: https://book.go-admin.cn/en/admin-plugins

As for the sidebar, you can use the built-in `menu` page to manage what you want to show graphically, I think GoAdmin store a list in its default database.

**Comment by MarErm27** [comment]
@haoyuant  You said that it's not hard to implement email function, may I ask, where to put it? I probably can make a special handler for realization in GO, but wherein the template of GoAdmin to add it? I mean in the interface

**Comment by haoyuant** [comment]
I mean, the code to send emails is not hard, I assume you want to have a button or something on the admin portal by clicking which you can send an email to all users, in that case, actually the challenge is to change the UI. I am not sure where you are going to place this UI, but I assume when you are generating the table, you can add UI controls to the form and handle the event yourself. Actually, in our project, we only add basic customisation and business logic to GoAdmin, like input verification, change field input style and visibility.

**Comment by MarErm27** [comment]
Is GoAdmin is free to use? Have you changed labels like  "All rights reserved. GoAdmin" and "Powered by GoAdmin"?

**Comment by haoyuant** [comment]
Yes, we did change this label, but maybe you should double-check its license.

**Comment by MarErm27** [comment]
There is a web site written in Node.js, is it possible to add my web application written in GO to extend it? Something like PrettyGhophers.com/MyAdminPortal

Where PrettyGhophers.com is written in Node.js

and /MyAdminPortal is my GO application written with GoAdmin framework

**Comment by MarErm27** [comment]
Hi, I'm trying to deploy my app at Google Cloud the way shown [here](https://www.youtube.com/watch?v=uL1YERoqGQc)
Exept I use go module

But it returns an error

go build github.com/MarErm27/adminPortal: copying /tmp/go-build643598888/b001/exe/a.out: open adminPortal: permission denied

I was wondering if you know how to give it permissions


I also tried to deploy it with command
gcloud app deploy

It is deployed and gave me the link but the link didn't responded at any port I tryed

**Comment by MarErm27** [comment]
I changed the owner of the directory with my project to my user and I able to run it with command go run main.go
Go build is still not working
I left my computer turned on for night but when I wake up the site didn't work. The google console was closed.
Is it possible to deploy my site so it will work independently from my computer?

I've tried a command "gcloud app deploy" it said that the deployment was successful, gave me the link to the site that don't respond to requests

Is there another way?

**Comment by haoyuant** [comment]
> There is a web site written in Node.js, is it possible to add my web application written in GO to extend it? Something like PrettyGhophers.com/MyAdminPortal
> 
> Where PrettyGhophers.com is written in Node.js
> 
> and /MyAdminPortal is my GO application written with GoAdmin framework

AFAIK, no you cannot do this. You will need to have two hosts to host your node.js program and Go app separately.

**Comment by haoyuant** [comment]
I used AWS for my go app hosting instead of GCP, but at a glimpse of that Youtube video you post, there is a comment saying that `Really? Should not you deploy the binary file and create a service so that it runs 24/7, even after you close the terminal shell. If we deploy the binary we do not need to install go on the server.`, are you sure that tutorial is for how to actually deploy your app to GCP?

I am not sure what other methods you have tried, but I will highly recommend you to follow the CGP official tutorial to create a Go app, get the simple one works on GCP first, and then move to your own project. https://cloud.google.com/appengine/docs/standard/go/building-app

**Comment by haoyuant** [comment]
Also, make sure you have a valid IAM or permission when you use GCP, if you are under a team, the lack of permission will also incur weird issues.

**Comment by MarErm27** [comment]
Thank you very much!

I've deployed it with GCloud app engine, here is the link
https://admin-portal-288918.ue.r.appspot.com/admin

Aren't the login page looks beautiful?

I was wondering if you know how to give it another name?

**Comment by MarErm27** [comment]
@haoyuant 
Hi, I've added a function to send emails the way shown below. So it just fetches the emails from the checked rows of the table and opens the default application to send an email.

I was wondering if you may guide me with the database. I've used a custom data source for the table, connected to Firebase, and fetched the data to the users table. But I haven't yet stepped put from using the SQLite. And I have a problem with SQLite: when I deployed the app to GCloud it appears that it's not possible to use SQLite there. It's just a read-only file there. 

`	script := `You can send emails in your default application for emails.

	<script>
		column = $('th:contains(Email)')[0];
		row = $('tr:contains(Email)')[0].children
		var emailColumnN;
		for (i = 0; i < row.length; i++) {
			if (row[i] === column){
				emailColumnN = i;
				break;
			}
		}
		currentNow = $("input:checked.grid-row-checkbox")
		var sendTo = ""
		for (i = 0; i < currentNow.length; i++) {
			sendTo += currentNow[i].parentNode.parentNode.parentNode.children[emailColumnN].innerText;
			if (i != currentNow.length -1) {
				sendTo += ","
			}
		}
		window.open('mailto:' + sendTo, '_self')
	</script>`

	act := action.PopUp("/admin/popup", "Send emails", func(ctx *context.Context) (success bool, msg string, data interface{}) {
		// Access to the paramters:
		//
		// ctx.FormValue["id"]
		// ctx.FormValue["ids"]

		// The data return is the content of popup.
		return true, "", script
	})

	info := externalTable.GetInfo()
	info.AddButton("Send emails", icon.Save, act)`

**Comment by MarErm27** [comment]
I was wondering if you may introduce me to your colleague?

**Comment by haoyuant** [comment]
I am glad that you've got GoAdmin running. I don't think there is any SQLite hosting service on GCP but you can embedded it in your server's file system, not your binary. Theoretically, if your environment and permission setup are correct, you should be able to read/write the SQLite file like other normal text files.

**Comment by haoyuant** [comment]
I can introduce you to my teammate, but he does not speak English, I am afraid it is hard for you to communicate.

**Comment by haoyuant** [comment]
If you have complex features and want to get the full control of how your admin module works, I will recommend you to implement your own, that's also what we did in another project. Actually implementing an admin portal is not that hard, especially when you can leverage the power of Firebase to do authentication for you, and the rest is just database operations and UI rendering.

**Comment by MarErm27** [comment]
How to use Firebase authentication?

Yes, introduce me to your teammate, please. We can communicate through the translator

**Comment by haoyuant** [comment]
Nothing is better than the official guideline https://firebase.google.com/docs/auth.

**Comment by haoyuant** [comment]
Unfortunately, my teammate is too busy to answer your question.

**Comment by MarErm27** [comment]
Thank you the site works with systemd service

**Comment by MarErm27** [comment]
Hello!
The code below is how I implemented the table generator function. I used a custom data source.
Here is a place where I fetch the users:
`users, usersLenght := app.GetUsers()`

So for users table pagination, I return a list of users on the page.
`return users[from:to], usersLenght`
If I would do this
`return users, usersLenght` or `return users, 10`
It will display all the list of users on each page.

I've got a problem with this pagination. So in the table of users, I can check rows with users. But when I go to another page the checked users from the previous page just becomes unchecked. **But the users from the previous page have to stay checked.** This is crucial because I've got a function to send emails, so you can navigate throw the user table choose users and you have to be able to send emails to all of them.

I was wondering if you know how to make the pagination work this way?

```
// GetFirebaseUserTable return the model from external data source.
func GetFirebaseUserTable(ctx *context.Context) (externalTable table.Table) {
	//query := ctx.Request.URL.Query()
	var page int
	var pageSize int
	var err error

	externalTable = table.NewDefaultTable(table.DefaultConfig())

	script := `You can send emails in your default application for emails.

	<script>
		column = $('th:contains(Email)')[0];
		row = $('tr:contains(Email)')[0].children
		var emailColumnN;
		for (i = 0; i < row.length; i++) {
			if (row[i] === column){
				emailColumnN = i;
				break;
			}
		}
		currentNow = $("input:checked.grid-row-checkbox")
		var sendTo = ""
		for (i = 0; i < currentNow.length; i++) {
			sendTo += currentNow[i].parentNode.parentNode.parentNode.children[emailColumnN].innerText;
			if (i != currentNow.length -1) {
				sendTo += ","
			}
		}
		window.open('mailto:' + sendTo, '_self')
	</script>`

	act := action.PopUp("/admin/popup", "Send emails", func(ctx *context.Context) (success bool, msg string, data interface{}) {
		// Access to the paramters:
		//
		// ctx.FormValue["id"]
		// ctx.FormValue["ids"]

		// The data return is the content of popup.
		return true, "", script
	})

	info := externalTable.GetInfo()
	info.AddButton("Send emails", icon.Save, act)
	info.AddField("Number", "id", db.Int).FieldSortable()
	info.AddField("Name", "name", db.Varchar).FieldSortable()
	info.AddField("Email", "email", db.Varchar)
	info.AddField("Phone", "phone", db.Varchar)
	info.AddField("Law Firm Chosen", "lawFirmChosen", db.Varchar)
	info.AddField("Last Activity", "lastActivity", db.Date)
	users, usersLenght := app.GetUsers()

	info.SetTable("users").
		SetTitle("Users").
		SetDescription("Users").
		SetGetDataFn(func(param parameter.Parameters) ([]map[string]interface{}, int) {

			page, err = strconv.Atoi(param.Page)
			if err == nil {
				fmt.Printf("i=%d, type: %T\n", param.Page, param.Page)
			}

			pageSize, err = strconv.Atoi(param.PageSize)
			if err == nil {
				fmt.Printf("i=%d, type: %T\n", param.PageSize, param.PageSize)
			}

			from := (page - 1) * pageSize
			to := page * pageSize
			if to > usersLenght {
				to = usersLenght
			}
			sortField := param.SortField
			if !(sortField == "id" && param.SortType == "asc") {
				sort.Slice(users,
					func(i, j int) bool {
						var orderDirection bool
						if sortField == "id" {
							if param.SortType != "asc" {
								orderDirection = users[i][sortField].(int) < users[j][sortField].(int)
							} else {
								orderDirection = users[i][sortField].(int) > users[j][sortField].(int)
							}
						} else if sortField == "name" {
							if param.SortType != "asc" {
								orderDirection = strings.ToLower(users[i][sortField].(string)) < strings.ToLower(users[j][sortField].(string))
							} else {
								orderDirection = strings.ToLower(users[i][sortField].(string)) > strings.ToLower(users[j][sortField].(string))
							}
						}
						return orderDirection
					})

			}
			return users[from:to], usersLenght
		})

	formList := externalTable.GetForm()
	formList.AddField("ID", "id", db.Int, form.Default).FieldDisplayButCanNotEditWhenUpdate().FieldDisableWhenCreate()
	formList.AddField("Name", "name", db.Varchar, form.Text)

	formList.SetTable("users").SetTitle("Users").SetDescription("Users")

	detail := externalTable.GetDetail()

	detail.SetTable("users").
		SetTitle("Users").
		SetDescription("Users").
		SetGetDataFn(func(param parameter.Parameters) ([]map[string]interface{}, int) {
			return []map[string]interface{}{
				{
					"id":   usersLenght,
					"name": "this is a name",
				},
			}, 1
		})

	return
}
```

**Comment by MarErm27** [comment]
### Description [describe your questions]
I need to keep the checked rows checked and to store list of checked emails. It is used for the sending emails functions. I haven't found a build-in function to I wrote a JS script that uses a LocalStorage. The code is below.

How do I add my custom JS to the page with a table of users? I can't find any HTML files where to look it for?

### Example code [If you have any code info]
column = $('th:contains(Email)')[0];
row = $('tr:contains(Email)')[0].children
var emailColumnN;
for (i = 0; i < row.length; i++) {
    if (row[i] === column) {
        emailColumnN = i;
        break;
    }
}

oldArray = localStorage.getItem("sendTo").split(",");


var event = document.createEvent("HTMLEvents");
event.initEvent('change', false, true);

rows = $("input.grid-row-checkbox")
for (i = 0; i < rows.length; i++) {
    email = rows[i].parentNode.parentNode.parentNode.children[emailColumnN].innerText;
    if (oldArray.includes(email)) {
        rows[i].checked = true
        rows[i].dispatchEvent(event)
        $(rows[i]).closest('div')[0].classList.add("checked");
    }
}

$('ins.iCheck-helper').bind("click", function () {

    var res = []
    currentNow = $("input:checked.grid-row-checkbox")
    var sendTo = []
    for (i = 0; i < currentNow.length; i++) {
        sendTo.push(currentNow[i].parentNode.parentNode.parentNode.children[emailColumnN].innerText);
    }

    sendTo = sendTo.concat(oldArray);
    res = Array.from(new Set(sendTo))

    currentUnchecked = $("input:not(:checked).grid-row-checkbox")
    var notSendTo = []
    for (i = 0; i < currentUnchecked.length; i++) {
        notSendTo.push(currentUnchecked[i].parentNode.parentNode.parentNode.children[emailColumnN].innerText);

    }
    var myArray = res.filter((item) => !notSendTo.includes(item));

    localStorage.setItem("sendTo", myArray.toString())

    //alert(myArray.length - 1);
});

### Others [screenshots or other info]
Please, help

**Comment by MarErm27** [comment]
Hi! I'm trying to update my VMinstance, my site works, but I got the error with I'm trying to connect to SSH console, I was wondering if you know how to fix it?

Connecting...
Transferring SSH keys to the VM.
The key transfer to project metadata is taking an unusually long time. Transferring instead to instance metadata may be faster, but will transfer the keys only to this VM. If you wish to SSH into other VMs from this VM, you will need to transfer the keys accordingly.
Click here to transfer the key to instance metadata. Note that this setting is persistent and needs to be disabled in the Instance Details page once enabled.

**Comment by MarErm27** [comment]
The access was restored after I enabled "OS Login"

**Comment by haoyuant** [comment]
Sorry I am not working on any Go project at the moment, and I am not familiar with the best practices to solve your problem. But yes, html and js are hard to find in GoAdmin, that's why we just create our own in other projects. Can you hook the checkbox to your Go code? If yes, you can trigger a callback and store the checked list in your Go code, and restore the check status when you flip the pages. There might be a better way for your case, but this is what I can think of in a short time without touching the generated html and js code.

**Comment by MarErm27** [comment]
Hello, Haoyuant!
I'm trying to create a tunnel for the MySQL database in Java. For the first step, I'm trying to create a tunnel from my localhost 3307 to 3308. So I have MySQL 5.6 running at localhost 3307 and I'm trying to make it available at 3308.
I'm using this library
https://mvnrepository.com/artifact/com.jcraft/jsch/0.1.55
I'm using this code to initialize the tunnel and it gives no errors.
```
    private void initSession() {
        System.out.println("initSession");
        try {
            JSch jsch = new JSch();
            AccessorPropertyDescriptor conf;

            session = jsch.getSession("127.0.0.1");

            Properties config = new Properties();
            config.put("StrictHostKeyChecking", "no");
            session.setConfig(config);
            try {
                session.setPortForwardingL(
                        3308,
                        "127.0.0.1",
                        3307
                );
            } catch (JSchException e) {
                e.printStackTrace();
            }
        } catch (JSchException e) {
            System.out.println("initSession fail");
            e.printStackTrace();
        }
    }
```
Here is a function to test the connection:
```
   private void checkSession() throws JSchException {
        System.out.println("checkSession");
        ChannelExec testChannel = null;
        System.out.println("testChannel");
        testChannel = (ChannelExec) session.openChannel("exec");
        System.out.println("openChannel");
        testChannel.setCommand("true");
        System.out.println("setCommand");
        testChannel.connect();
        System.out.println("connect");
        testChannel.disconnect();
        System.out.println("disconnect");
    }
```
Here is an error
```
initSession
checkSession
testChannel
checkSession error
com.jcraft.jsch.JSchException: session is down
        at com.jcraft.jsch.Session.openChannel(Session.java:861)
        at com.qbwc.service.ServiceWatchMaxxQB.checkSession(ServiceWatchMaxxQB.java:200)
        at com.qbwc.service.ServiceWatchMaxxQB.init(ServiceWatchMaxxQB.java:223)
        at org.apache.axis2.engine.DependencyManager.initServiceObject(DependencyManager.java:65)
        at org.apache.axis2.receivers.AbstractMessageReceiver.getTheImplementationObject(AbstractMessageReceiver.java:212)
        at com.qbwc.service.AxisMessageReceiverInOut.invokeBusinessLogic(AxisMessageReceiverInOut.java:33)
        at org.apache.axis2.receivers.AbstractInOutMessageReceiver.invokeBusinessLogic(AbstractInOutMessageReceiver.java:40)
        at org.apache.axis2.receivers.AbstractMessageReceiver.receive(AbstractMessageReceiver.java:106)
        at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:169)
        at org.apache.axis2.transport.http.HTTPTransportUtils.processHTTPPostRequest(HTTPTransportUtils.java:178)
        at org.apache.axis2.transport.http.AxisServlet.doPost(AxisServlet.java:164)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```
so the error happens at this line:
```
testChannel = (ChannelExec) session.openChannel("exec");
```
I was wondering if you know how to make work?

**Comment by MarErm27** [comment]
Hello! I was wondering if you may advise me on how to find a remote job. 
May I send you my CV to your email?

**Comment by haoyuant** [comment]
Sure, if you are okay with that, I can have a look when I am free.

**Comment by MarErm27** [comment]
May you let me know your email?

**Comment by haoyuant** [comment]
Sure, haoyuant94718@gmail.com
